### ISSUE TITLE
Remove visible link icon for table captions

### ISSUE THREAD

**Issue by Mrt134** [Mrt134/Test-New-Sphinx-Theme#2]
Appearance should be invisible unless the table caption is hovered over (see header links for an example of the desired functionality).

**Comment by ZackaryWelch** [comment]
Table caption has been changed to work as the header links.
https://github.com/Mrt134/Test-New-Sphinx-Theme/commit/8d73f9e71b0a67a0c982e4fcae9a01aee7c7b517
